#!/bin/sh

getent group pulse || /usr/sbin/groupadd -r pulse
getent passwd pulse || /usr/sbin/useradd -r -g pulse -d /var/run/pulse -s /sbin/nologin -c "Pulseaudio System User" pulse
/usr/bin/passwd -l pulse > /dev/null
